"""initial schema

Revision ID: 8aafcffee773
Revises:
Create Date: 2026-09-27 14:17:12.578148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8aafcffee773"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_table(
        "ingest_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status in ('running', 'succeeded', 'stopped', 'failed')",
            name=op.f("ck_ingest_run_status_known"),
        ),
        sa.CheckConstraint(
            "pages >= 0 and records >= 0", name=op.f("ck_ingest_run_counters_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_run")),
    )
    op.create_index(
        "ix_ingest_run_entity_started", "ingest_run", ["entity", "started_at"], unique=False
    )
    op.create_table(
        "ref_classifier",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("parent_code", sa.String(length=32), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=512), nullable=False),
        sa.Column("name_kk", sa.String(length=512), nullable=True),
        sa.CheckConstraint("code <> parent_code", name=op.f("ck_ref_classifier_no_self_parent")),
        sa.CheckConstraint("level >= 0", name=op.f("ck_ref_classifier_level_non_negative")),
        sa.ForeignKeyConstraint(
            ["parent_code"],
            ["ref_classifier.code"],
            name=op.f("fk_ref_classifier_parent_code_ref_classifier"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_ref_classifier")),
    )
    op.create_index(
        "ix_ref_classifier_parent_code", "ref_classifier", ["parent_code"], unique=False
    )
    op.create_table(
        "ref_status",
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("name_ru", sa.String(length=256), nullable=False),
        sa.Column("name_kk", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("domain", "code", name=op.f("pk_ref_status")),
    )
    op.create_table(
        "sync_state",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("cursor", sa.String(length=128), nullable=True),
        sa.Column("watermark", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_done", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_done", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("finished", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source", "entity", name=op.f("pk_sync_state")),
    )
    op.create_table(
        "saved_filter",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_saved_filter_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_filter")),
        sa.UniqueConstraint("user_id", "name", name="uq_saved_filter_user_id_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saved_filter")
    op.drop_table("sync_state")
    op.drop_table("ref_status")
    op.drop_index("ix_ref_classifier_parent_code", table_name="ref_classifier")
    op.drop_table("ref_classifier")
    op.drop_index("ix_ingest_run_entity_started", table_name="ingest_run")
    op.drop_table("ingest_run")
    op.drop_table("app_user")
    # ### end Alembic commands ###
